credebl/adeya-wallet

app/screens/OnboardingPages.tsx
Resolved  text-missing issue  for onBoarding last screen.
=> fix:#97issue-text-missing

app/components/views/HomeContentView.tsx
Resolved  connection count   issue on Home-screen.
=> fix:contact-count-#100

app/components/inputs/LimitedTextInput.tsx
=> refactor:LimitedTextInput.tsx

app/screens/ExportWalletConfirmation.tsx, app/screens/ImportWalletConfirmation.tsx, app/screens/Success.tsx
Resolved export wallet Android version 10.
=> Resolving backup wallet #112

app/components/inputs/LimitedTextInput.tsx, app/components/misc/UnorderedList.tsx, app/components/modals/CameraDisclosureModal.tsx, app/components/modals/CommonRemoveModal.tsx, app/components/views/HomeContentView.tsx, app/localization/en/index.ts, app/screens/CredentialOffer.tsx, app/screens/ProofRequest.tsx, app/screens/Settings.tsx, app/types/settings.ts
=> Suggested changhes wallet name#114

android/app/build.gradle, android/app/src/debug/java/id/credebl/adeya/ReactNativeFlipper.java, android/app/src/main/java/id/credebl/adeya/MainActivity.java, android/app/src/main/java/id/credebl/adeya/MainApplication.java, android/app/src/release/java/id/credebl/adeya/ReactNativeFlipper.java
1. Renamed package name adeyawallet to id.credeble.adeya
=> chore:rename package name adeyawallet to id.credeble.adeya

app/screens/ExportWalletConfirmation.tsx
1. resolved seed phrase sequence should be random .
=> Testing reported issue

app/localization/fr/index.ts, app/localization/pt-br/index.ts, app/screens/CredentialOffer.tsx, app/screens/ImportWalletConfirmation.tsx, app/screens/ProofRequest.tsx, app/screens/WhatAreContacts.tsx, patches/@aries-framework+askar+0.4.0.patch, yarn.lock
1. fix Import wallet issue if user cancel to import again create wallet.
2. Removed Added contacts from credential offer
3. Removed Added contacts from proof request.
4. Update contact text content in setting menu.
=> Resolve wallet initialize bug

.github/pull_request_template.md
=> docs: create pull request template

app/utils/helpers.ts
- removed adjective name random wallet name
Na
=> refactor: removed adjectives while generating random wallet name

app/components/inputs/PINInput.tsx, app/screens/ImportWalletConfirmation.tsx, app/screens/PINEnter.tsx
- resolve cursor blinked on pin enter screen after  biometric  enable
- resolve on scroll drag verify button on import wallet screen
NA
=> fix: blinking pin enter cursor

android/app/src/main/res/values/strings.xml, app.json, ios/AdeyaWallet.xcodeproj/project.pbxproj, ios/AdeyaWallet/Info.plist
=> refactor: app name

android/app/src/main/AndroidManifest.xml, ios/AdeyaWallet/AppDelegate.mm, ios/AdeyaWallet/Info.plist
-Added deep linking support 
https://github.com/credebl/adeya-wallet/issues/100
https://github.com/credebl/adeya-wallet/issues/101
=> Deep linking

.env.sample, app/api/organizationDetailHelper.ts, app/components/listItems/ContactListItem.tsx, app/components/listItems/OrganizationListItem.tsx, app/navigators/OrganizationStack.tsx, app/navigators/TabStack.tsx, app/screens/Chat.tsx, app/screens/OrganizationDetails.tsx, app/types/navigators.ts
- Fixed navigation between organization screens
- Fixed sorting issue in the `Chat` and `Contact Details` screen
=> fix: explore org navigation

app/api/Organization.ts, app/localization/en/index.ts, app/navigators/RootStack.tsx, app/screens/ContactDetails.tsx, app/screens/ImportWalletConfirmation.tsx, app/screens/ProofRequest.tsx, app/screens/ProofRequesting.tsx, app/screens/Scan.tsx, app/utils/helpers.ts, ios/AdeyaWallet.xcodeproj/project.pbxproj, package.json, yarn.lock
- fixed the import wallet failure scenario
- fixed issue for a condition where connection already exists
=> fix: import wallet failure scenario

android/app/src/main/AndroidManifest.xml, ios/AdeyaWallet/AdeyaWallet.entitlements, ios/AdeyaWallet/Info.plist
- Add deep link configuration for Android and iOS for dev environment
=> feat: add dev deep link configuration

app/screens/OrganizationDetails.tsx, app/screens/Scan.tsx, app/utils/PushNotificationHelper.ts, app/utils/helpers.ts
- Added URL shortening support for invitations
=> feat: add url shortening support

App.tsx, android/app/src/main/AndroidManifest.xml, app/components/misc/SharedProofData.tsx, app/screens/ListCredentials.tsx, app/screens/ProofChangeCredential.tsx, app/screens/ProofRequest.tsx, app/utils/credential.ts, ios/AdeyaWallet/Info.plist
- Fix proof predicate issue
- Deeplink URL prefix
- Buffer issue in wallet backup
NA
=> fix: proof predicate issue

android/app/build.gradle, ios/AdeyaWallet.xcodeproj/project.pbxproj, ios/Podfile.lock
- Bump Android and iOS version
- Update `Podfile.lock` file
=> chore: bump iOS version

README.md
your changes text, screenshot or small recording
docs: add discord link #62   
add ticket link
https://github.com/credebl/adeya-wallet/issues/62
=> Updating join community links

app/screens/OnboardingPages.tsx, app/screens/ProofRequest.tsx, app/screens/Splash.tsx
- Fixed the changing of credential if multiple credentials exist
=> fix: change credential in proof request

app/components/record/W3CCredentialRecord.tsx, app/screens/CredentialDetails.tsx, app/screens/CredentialDetailsW3C.tsx, app/screens/CredentialOffer.tsx, app/screens/ListContacts.tsx, app/screens/ProofRequest.tsx
- Improved UI in W3CCredential details
- Show only completed connections
=> refactor: improve UI in W3CCredential details

android/app/src/main/AndroidManifest.xml, app/navigators/RootStack.tsx, ios/AdeyaWallet.xcodeproj/project.pbxproj, ios/AdeyaWallet/AdeyaWallet.entitlements, ios/AdeyaWallet/Info.plist
- Updated the deeplink urls
- Added logic to handle shorten urls
=> refactor: update deep link urls

app/screens/CredentialOffer.tsx, app/utils/helpers.ts, package.json, yarn.lock
- Negotiate w3c credential offer
=> feat: negotiate w3c credential offer

android/app/build.gradle, app/screens/CredentialDetailsW3C.tsx, ios/AdeyaWallet.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
=> fix: padding in pdfs

app/components/modals/CommonRemoveModal.tsx
Unable to enter reason for declining proof request in IOS
=> fix: Unable to enter reason for declining proof request in IOS
